aci_items:
  # defines tenant(s)
  - fvTenant:
      attributes:
        name: TN_PEHRUBY_TEST
        descr: "PH Tes tenant"

  # defines VRF(s)
  - fvCtx:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      attributes:
        name: VRF_PH01
  - fvCtx:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      attributes:
        name: VRF_PH02

  # defines BD(s)
  - fvBD:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      attributes:
        name: BD_PH01

  # binds VRFs to BDs
  - fvRsCtx:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      fvBD: 
        name: BD_PH01
      attributes:
        tnFvCtxName: VRF_PH01

  # defines AP
  - fvAp:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      attributes:
        name: AP_PHTEST

  # defines App EPG
  - fvAEPg:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      fvAp: 
        name: AP_PHTEST
      attributes:
        name: EPG_AP-PH
  - fvAEPg:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      fvAp: 
        name: AP_PHTEST
      attributes:
        name: EPG_AP-PH2

  # attach ports to EPG
  - fvRsNodeAtt:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      fvAp: 
        name: AP_PHTEST
      fvAEPg: 
        name: EPG_AP-PH
      attributes:
        tDn: topology/pod-1/node-101
        encap: vlan-23
  - fvRsNodeAtt:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      fvAp: 
        name: AP_PHTEST
      fvAEPg: 
        name: EPG_AP-PH
      attributes:
        tDn: topology/pod-1/node-102
        encap: vlan-23
  
  # defines contract 
  - vzBrCP: 
      fvTenant: 
        name: TN_PEHRUBY_TEST   # vrf scoped (default)
      attributes:
        name: CON_PH01
  - vzBrCP: 
      fvTenant: 
        name: TN_PEHRUBY_TEST 
      attributes:
        name: CON_TEN_PH02
        scope: tenant         # tenant scoped

  # defines contract subject 
  - vzSubj:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      vzBrCP: 
        name: CON_PH01
      attributes:
        name: CS_PHTEST
  
  # define filter
  - vzFilter:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      attributes:
        name: FIL_PHTEST
  
  # define filter entry
  - vzEntry:
      fvTenant: 
        name: TN_PEHRUBY_TEST
      vzFilter: 
        name: FIL_PHTEST
      attributes:
        name: FE_PH-HTTP
        etherT: ipv4
        prot: tcp
        dFromPort: http
        dToPort: http










